### ISSUE TITLE
Push hangs, error on pull

### ISSUE THREAD

**Issue by ar4** [rakyll/drive#38]
Drive hangs when I try to push a file, using about 100% of one CPU core, and when I run drive pull I get the following output:

Resolving...
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0xb773ac7c

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x18982e48)
        /usr/lib/go/src/pkg/runtime/sema.goc:199 +0x34
sync.(_WaitGroup).Wait(0x18972f20)
        /usr/lib/go/src/pkg/sync/waitgroup.go:127 +0x12a
github.com/rakyll/drive.(_Commands).resolveChangeListRecv(0x1880a470, 0x0, 0x188005e0, 0x1, 0x189adc00, ...)
        /home/alanr/gocode/src/github.com/rakyll/drive/changes.go:86 +0x3d6
github.com/rakyll/drive.(_Commands).Pull(0x1880a470, 0x0, 0x0)
        /home/alanr/gocode/src/github.com/rakyll/drive/pull.go:45 +0x193
main.(_pullCmd).Run(0x188004e8, 0x1880a010, 0x0, 0x0)
        /home/alanr/gocode/src/github.com/rakyll/drive/cmd/drive/main.go:75 +0xb3
github.com/rakyll/command.Run()
        /home/alanr/gocode/src/github.com/rakyll/command/command.go:155 +0x70
github.com/rakyll/command.ParseAndRun()
        /home/alanr/gocode/src/github.com/rakyll/command/command.go:162 +0x23
main.main()
        /home/alanr/gocode/src/github.com/rakyll/drive/cmd/drive/main.go:45 +0x68d

...

I am using a clean install of Lubuntu 14.10.

**Comment by fergald** [comment]
I've hitting the same issue (I've had it from diff, pull and push). I have 8G of RAM and the machine is doing very little else. From some other searching, it may be that there are too many threads, caused by too many goroutines. The stack trace I got has 606 goroutines in it. Also, sometimes the the commands work just fine. So it seems like some kind of random element is involved. Perhaps if the network is fast the goroutines complete quickly and don't accumulate but if it's slow, the backlog builds up and eventually exceeds a thread-limit.

(I'm on Ubuntu 14.04)

**Comment by pmig** [comment]
@fergald I recommend you using this branch: https://github.com/odeke-em/drive. Emmanuel did serval significant improvements.

**Comment by fergald** [comment]
I already am :(.

Should I reopen this bug on the other project?

**Comment by fergald** [comment]
Ah, already there.

https://github.com/odeke-em/drive/issues/22
